name: CI/CD Deploy vattukc.com

on:
  push:
    branches:
      - main   # Tá»± Ä‘á»™ng cháº¡y khi push code lÃªn nhÃ¡nh main

jobs:
  build:
    name: ğŸ§± Build Project
    runs-on: ubuntu-latest

    steps:
      - name: ğŸŒ€ Checkout source code
        uses: actions/checkout@v4

      - name: ğŸŸ¡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ“¦ Install dependencies
        working-directory: client
        run: npm ci

      - name: ğŸ— Build Next.js project
        working-directory: client
        run: npm run build

